/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as TableTableNumberRouteImport } from './routes/table.$tableNumber'
import { Route as SiteReserveRouteImport } from './routes/_site.reserve'
import { Route as SiteMenuRouteImport } from './routes/_site.menu'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteEventsRouteImport } from './routes/_site.events'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteBarRouteImport } from './routes/_site.bar'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const TableTableNumberRoute = TableTableNumberRouteImport.update({
  id: '/table/$tableNumber',
  path: '/table/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteReserveRoute = SiteReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMenuRoute = SiteMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventsRoute = SiteEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBarRoute = SiteBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/reception': typeof ReceptionRoute
  '/about': typeof SiteAboutRoute
  '/bar': typeof SiteBarRoute
  '/contact': typeof SiteContactRoute
  '/events': typeof SiteEventsRoute
  '/gallery': typeof SiteGalleryRoute
  '/menu': typeof SiteMenuRoute
  '/reserve': typeof SiteReserveRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/reception': typeof ReceptionRoute
  '/about': typeof SiteAboutRoute
  '/bar': typeof SiteBarRoute
  '/contact': typeof SiteContactRoute
  '/events': typeof SiteEventsRoute
  '/gallery': typeof SiteGalleryRoute
  '/menu': typeof SiteMenuRoute
  '/reserve': typeof SiteReserveRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/reception': typeof ReceptionRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/bar': typeof SiteBarRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/events': typeof SiteEventsRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/menu': typeof SiteMenuRoute
  '/_site/reserve': typeof SiteReserveRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reception'
    | '/about'
    | '/bar'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/menu'
    | '/reserve'
    | '/table/$tableNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/reception'
    | '/about'
    | '/bar'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/menu'
    | '/reserve'
    | '/table/$tableNumber'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/reception'
    | '/_site/about'
    | '/_site/bar'
    | '/_site/contact'
    | '/_site/events'
    | '/_site/gallery'
    | '/_site/menu'
    | '/_site/reserve'
    | '/table/$tableNumber'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ReceptionRoute: typeof ReceptionRoute
  TableTableNumberRoute: typeof TableTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/table/$tableNumber': {
      id: '/table/$tableNumber'
      path: '/table/$tableNumber'
      fullPath: '/table/$tableNumber'
      preLoaderRoute: typeof TableTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/reserve': {
      id: '/_site/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof SiteReserveRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/menu': {
      id: '/_site/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof SiteMenuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/events': {
      id: '/_site/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof SiteEventsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bar': {
      id: '/_site/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof SiteBarRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBarRoute: typeof SiteBarRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteEventsRoute: typeof SiteEventsRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SiteMenuRoute: typeof SiteMenuRoute
  SiteReserveRoute: typeof SiteReserveRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBarRoute: SiteBarRoute,
  SiteContactRoute: SiteContactRoute,
  SiteEventsRoute: SiteEventsRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SiteMenuRoute: SiteMenuRoute,
  SiteReserveRoute: SiteReserveRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
  ReceptionRoute: ReceptionRoute,
  TableTableNumberRoute: TableTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
